# infra/prometheus.yml

global:
  scrape_interval: 15s # Raspar métricas cada 15 segundos

scrape_configs:
  # Job para el propio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job para tu Aplicación Node.js/Express
  - job_name: 'app_service'
    # La aplicación se ejecuta en el host local del runner en el puerto 8080
    static_configs:
      - targets: ['proyecto1-app:8080']
